# Generated by Django 5.0.4 on 2024-06-07 10:08

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название языка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/lang_images', verbose_name='Значок ЯП')),
                ('url', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Font awesome icon')),
            ],
            options={
                'verbose_name': 'ЯП',
                'verbose_name_plural': 'ЯПы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название поста')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='media/previews', verbose_name='Изображение к посту для ленты')),
                ('url', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Контент')),
                ('preview_description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True)),
                ('time_created', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название изображения')),
                ('image', models.ImageField(upload_to='media/post_images', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя тега')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, default='Информация скоро обновится', null=True, verbose_name='Описание')),
                ('url', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Font Awesome Icon')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
