# Generated by Django 5.0.4 on 2024-06-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_description',
            field=models.TextField(default=True, verbose_name='Описание'),
        ),
    ]
