# Generated by Django 5.0.4 on 2024-05-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='Информация скоро обновится', null=True, verbose_name='Описание'),
        ),
    ]
