# Generated by Django 5.0.4 on 2024-05-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='language',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Font awesome icon'),
        ),
    ]
