# Generated by Django 5.0.4 on 2024-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/previews', verbose_name='Изображение к посту для ленты'),
        ),
    ]
