# Generated by Django 5.0.4 on 2024-05-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_level_post_lft_post_rght_post_tree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='level',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tree_id',
        ),
    ]
