# Generated by Django 5.0.4 on 2024-10-02 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
                ('time_created', models.DateField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предложенная статья',
                'verbose_name_plural': 'Предложеннае статьи',
                'ordering': ['-time_created'],
            },
        ),
    ]
