# Generated by Django 5.0.4 on 2024-06-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_suggestarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestarticle',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработана'),
        ),
    ]
